### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by proffalken** [Hanyman8/OctoPrint-OAuth2#7]
Hi @Hanyman8,

Given there's not been an update to the code in 5 years, I'm assuming this is no longer maintained?

I've got a use-case for this plugin and I'd be interested in seeing how much effort would be required to bring it up to the latest version of octoprint and python - if you can share any thoughts you have on that I'd appreciate it!

Thanks in advance. :)

**Comment by Hanyman8** [comment]
Hello, yes, it is no longer maintained. It was used for the Octoprint version 5 years ago, but at that time it still had some issues.

I haven't seen Octoprint for 3 years maybe. I don't have much time for 3D printing anymore and when I do, I use SD cards.

Feel free to fork this repo and fix it :)

**Comment by proffalken** [comment]
Thanks - I gave it a go at fixing it, but the auth layer seems to be tied very tightly to the "built-in" basic auth.

I may well come back to this in future for ideas though!
